//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50401.0
// 
namespace PostAlbum.PostAlbumService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PostAlbumService.AlbumSoap")]
    public interface AlbumSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState);
        
        string EndHelloWorld(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetAttachList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttachmentInfo))]
        System.IAsyncResult BeginGetAttachList(int topicid, int forumid, string onlyauthor, int posterid, PostAlbum.PostAlbumService.CredentialInfo creinfo, System.AsyncCallback callback, object asyncState);
        
        ShowtopicPageAttachmentInfo[] EndGetAttachList(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CredentialInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string authTokenField;
        
        private int userIDField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AuthToken {
            get {
                return this.authTokenField;
            }
            set {
                this.authTokenField = value;
                this.RaisePropertyChanged("AuthToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ShowtopicPageAttachmentInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AttachmentInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int aidField;
        
        private int uidField;
        
        private int tidField;
        
        private int pidField;
        
        private string postdatetimeField;
        
        private int readpermField;
        
        private string filenameField;
        
        private string descriptionField;
        
        private string filetypeField;
        
        private long filesizeField;
        
        private string attachmentField;
        
        private int downloadsField;
        
        private int attachpriceField;
        
        private int widthField;
        
        private int heightField;
        
        private int sys_indexField;
        
        private string sys_nouploadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Aid {
            get {
                return this.aidField;
            }
            set {
                this.aidField = value;
                this.RaisePropertyChanged("Aid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
                this.RaisePropertyChanged("Uid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Tid {
            get {
                return this.tidField;
            }
            set {
                this.tidField = value;
                this.RaisePropertyChanged("Tid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Pid {
            get {
                return this.pidField;
            }
            set {
                this.pidField = value;
                this.RaisePropertyChanged("Pid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Postdatetime {
            get {
                return this.postdatetimeField;
            }
            set {
                this.postdatetimeField = value;
                this.RaisePropertyChanged("Postdatetime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Readperm {
            get {
                return this.readpermField;
            }
            set {
                this.readpermField = value;
                this.RaisePropertyChanged("Readperm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
                this.RaisePropertyChanged("Filename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Filetype {
            get {
                return this.filetypeField;
            }
            set {
                this.filetypeField = value;
                this.RaisePropertyChanged("Filetype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public long Filesize {
            get {
                return this.filesizeField;
            }
            set {
                this.filesizeField = value;
                this.RaisePropertyChanged("Filesize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
                this.RaisePropertyChanged("Attachment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int Downloads {
            get {
                return this.downloadsField;
            }
            set {
                this.downloadsField = value;
                this.RaisePropertyChanged("Downloads");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int Attachprice {
            get {
                return this.attachpriceField;
            }
            set {
                this.attachpriceField = value;
                this.RaisePropertyChanged("Attachprice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("Width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("Height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int Sys_index {
            get {
                return this.sys_indexField;
            }
            set {
                this.sys_indexField = value;
                this.RaisePropertyChanged("Sys_index");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Sys_noupload {
            get {
                return this.sys_nouploadField;
            }
            set {
                this.sys_nouploadField = value;
                this.RaisePropertyChanged("Sys_noupload");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowtopicPageAttachmentInfo : AttachmentInfo {
        
        private int getattachpermField;
        
        private int attachimgpostField;
        
        private int allowreadField;
        
        private string previewField;
        
        private int isboughtField;
        
        private int insertedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Getattachperm {
            get {
                return this.getattachpermField;
            }
            set {
                this.getattachpermField = value;
                this.RaisePropertyChanged("Getattachperm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Attachimgpost {
            get {
                return this.attachimgpostField;
            }
            set {
                this.attachimgpostField = value;
                this.RaisePropertyChanged("Attachimgpost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Allowread {
            get {
                return this.allowreadField;
            }
            set {
                this.allowreadField = value;
                this.RaisePropertyChanged("Allowread");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Preview {
            get {
                return this.previewField;
            }
            set {
                this.previewField = value;
                this.RaisePropertyChanged("Preview");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Isbought {
            get {
                return this.isboughtField;
            }
            set {
                this.isboughtField = value;
                this.RaisePropertyChanged("Isbought");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Inserted {
            get {
                return this.insertedField;
            }
            set {
                this.insertedField = value;
                this.RaisePropertyChanged("Inserted");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AlbumSoapChannel : PostAlbum.PostAlbumService.AlbumSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAttachListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAttachListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ShowtopicPageAttachmentInfo[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ShowtopicPageAttachmentInfo[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlbumSoapClient : System.ServiceModel.ClientBase<PostAlbum.PostAlbumService.AlbumSoap>, PostAlbum.PostAlbumService.AlbumSoap {
        
        private BeginOperationDelegate onBeginHelloWorldDelegate;
        
        private EndOperationDelegate onEndHelloWorldDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAttachListDelegate;
        
        private EndOperationDelegate onEndGetAttachListDelegate;
        
        private System.Threading.SendOrPostCallback onGetAttachListCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public AlbumSoapClient() {
        }
        
        public AlbumSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlbumSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlbumSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlbumSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<HelloWorldCompletedEventArgs> HelloWorldCompleted;
        
        public event System.EventHandler<GetAttachListCompletedEventArgs> GetAttachListCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PostAlbum.PostAlbumService.AlbumSoap.BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorld(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string PostAlbum.PostAlbumService.AlbumSoap.EndHelloWorld(System.IAsyncResult result) {
            return base.Channel.EndHelloWorld(result);
        }
        
        private System.IAsyncResult OnBeginHelloWorld(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PostAlbum.PostAlbumService.AlbumSoap)(this)).BeginHelloWorld(callback, asyncState);
        }
        
        private object[] OnEndHelloWorld(System.IAsyncResult result) {
            string retVal = ((PostAlbum.PostAlbumService.AlbumSoap)(this)).EndHelloWorld(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldCompleted(object state) {
            if ((this.HelloWorldCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        public void HelloWorldAsync(object userState) {
            if ((this.onBeginHelloWorldDelegate == null)) {
                this.onBeginHelloWorldDelegate = new BeginOperationDelegate(this.OnBeginHelloWorld);
            }
            if ((this.onEndHelloWorldDelegate == null)) {
                this.onEndHelloWorldDelegate = new EndOperationDelegate(this.OnEndHelloWorld);
            }
            if ((this.onHelloWorldCompletedDelegate == null)) {
                this.onHelloWorldCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldDelegate, null, this.onEndHelloWorldDelegate, this.onHelloWorldCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PostAlbum.PostAlbumService.AlbumSoap.BeginGetAttachList(int topicid, int forumid, string onlyauthor, int posterid, PostAlbum.PostAlbumService.CredentialInfo creinfo, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAttachList(topicid, forumid, onlyauthor, posterid, creinfo, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ShowtopicPageAttachmentInfo[] PostAlbum.PostAlbumService.AlbumSoap.EndGetAttachList(System.IAsyncResult result) {
            return base.Channel.EndGetAttachList(result);
        }
        
        private System.IAsyncResult OnBeginGetAttachList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int topicid = ((int)(inValues[0]));
            int forumid = ((int)(inValues[1]));
            string onlyauthor = ((string)(inValues[2]));
            int posterid = ((int)(inValues[3]));
            PostAlbum.PostAlbumService.CredentialInfo creinfo = ((PostAlbum.PostAlbumService.CredentialInfo)(inValues[4]));
            return ((PostAlbum.PostAlbumService.AlbumSoap)(this)).BeginGetAttachList(topicid, forumid, onlyauthor, posterid, creinfo, callback, asyncState);
        }
        
        private object[] OnEndGetAttachList(System.IAsyncResult result) {
            ShowtopicPageAttachmentInfo[] retVal = ((PostAlbum.PostAlbumService.AlbumSoap)(this)).EndGetAttachList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAttachListCompleted(object state) {
            if ((this.GetAttachListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAttachListCompleted(this, new GetAttachListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAttachListAsync(int topicid, int forumid, string onlyauthor, int posterid, PostAlbum.PostAlbumService.CredentialInfo creinfo) {
            this.GetAttachListAsync(topicid, forumid, onlyauthor, posterid, creinfo, null);
        }
        
        public void GetAttachListAsync(int topicid, int forumid, string onlyauthor, int posterid, PostAlbum.PostAlbumService.CredentialInfo creinfo, object userState) {
            if ((this.onBeginGetAttachListDelegate == null)) {
                this.onBeginGetAttachListDelegate = new BeginOperationDelegate(this.OnBeginGetAttachList);
            }
            if ((this.onEndGetAttachListDelegate == null)) {
                this.onEndGetAttachListDelegate = new EndOperationDelegate(this.OnEndGetAttachList);
            }
            if ((this.onGetAttachListCompletedDelegate == null)) {
                this.onGetAttachListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAttachListCompleted);
            }
            base.InvokeAsync(this.onBeginGetAttachListDelegate, new object[] {
                        topicid,
                        forumid,
                        onlyauthor,
                        posterid,
                        creinfo}, this.onEndGetAttachListDelegate, this.onGetAttachListCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override PostAlbum.PostAlbumService.AlbumSoap CreateChannel() {
            return new AlbumSoapClientChannel(this);
        }
        
        private class AlbumSoapClientChannel : ChannelBase<PostAlbum.PostAlbumService.AlbumSoap>, PostAlbum.PostAlbumService.AlbumSoap {
            
            public AlbumSoapClientChannel(System.ServiceModel.ClientBase<PostAlbum.PostAlbumService.AlbumSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("HelloWorld", _args, callback, asyncState);
                return _result;
            }
            
            public string EndHelloWorld(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("HelloWorld", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAttachList(int topicid, int forumid, string onlyauthor, int posterid, PostAlbum.PostAlbumService.CredentialInfo creinfo, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[5];
                _args[0] = topicid;
                _args[1] = forumid;
                _args[2] = onlyauthor;
                _args[3] = posterid;
                _args[4] = creinfo;
                System.IAsyncResult _result = base.BeginInvoke("GetAttachList", _args, callback, asyncState);
                return _result;
            }
            
            public ShowtopicPageAttachmentInfo[] EndGetAttachList(System.IAsyncResult result) {
                object[] _args = new object[0];
                ShowtopicPageAttachmentInfo[] _result = ((ShowtopicPageAttachmentInfo[])(base.EndInvoke("GetAttachList", _args, result)));
                return _result;
            }
        }
    }
}
